# Generated by Django 3.1.2 on 2020-11-02 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myHood_Main', '0002_auto_20201101_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='CREATED_AT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='UPDATED_AT',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='CREATED_AT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hood',
            name='UPDATED_AT',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myHood_Main.hood')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myHood_Main.hood')),
            ],
        ),
    ]
