# Generated by Django 3.1.2 on 2020-11-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHood_Main', '0003_auto_20201102_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='lorem ipsum'),
            preserve_default=False,
        ),
    ]
